### ISSUE TITLE
remove nucleic acid type from database?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/adage-frontend#138]
*From Dallas Mould:*

Under sample details info about nucleic acid type is included. I think this unnecessary because they should all be RNA if we are looking at transcriptomics.

**Comment by vincerubinetti** [comment]
I'm not sure, but maybe in the future, when adage is used beyond pseudomonas, the nucleic acid type might be different between samples? @cgreene do we really need this field.

**Comment by cgreene** [comment]
It seems to me like it's pretty safe to assume RNA but I'm not sure how much it would require writing special rules to remove that or ignore it.

**Comment by vincerubinetti** [comment]
Not difficult for me, but if it's really never ever required, I'd recommend just removing it from the database. Solve the problem at its root, rather than hiding it. @dongbohu

**Comment by cgreene** [comment]
If the code is loading tab-delimited information that comes from an external source then I wouldn't write extra code to remove those fields. It seems pretty harmless to have it, and making our loading code more specific/brittle always worries me with regards to maintenance burden. If it turns out to be something we're specifically lookin for and removing, then I don't think we need to go grab that field.

**Comment by cgreene** [comment]
Although - actually - I'm remembering some experiments where groups hybed genomic DNA from different strains to these arrays to see what the background level intensities were like. Perhaps we should keep it.

**Comment by dongbohu** [comment]
`nucleic_acid` is one of the sample annotation types. It was populated during the process of reading in the external data files. I would prefer keeping it at this point. If we remove it now, it will be much more difficult to recover in the future.

**Comment by vincerubinetti** [comment]
Closing since it seems like we're keeping this
